<?php
declare(strict_types=1);

namespace phpbbseo\framework\Rewrite;

use phpbbseo\framework\Configuration\ConfigurationProvider;

/**
 * Compiles authoritatively defined permalink patterns into a lightweight PHP cache file
 * for ultra-fast, zero-overhead inbound route matching on the pre-bootstrap path.
 */
class CompiledInboundRouteCache
{
    public function __construct(
        private readonly PermalinkConfiguration $permalinkConfig,
        private readonly UrlPatternCompiler $compiler,
        private readonly ConfigurationProvider $configProvider,
        private readonly string $storeDirectory
    ) {}

    /**
     * Rebuild and save the compiled inbound routes cache file.
     * Returns the array of compiled routes.
     *
     * @return array<int, array<string, mixed>>
     */
    public function rebuild(): array
    {
        $groupPattern = $this->configProvider->get('seo_pattern_group', '/group/{slug}-{id}/');

        $patterns = [
            [
                'resource' => 'topic',
                'pattern'  => $this->permalinkConfig->getPattern('topic_page'),
                'required' => ['id', 'page'],
            ],
            [
                'resource' => 'topic',
                'pattern'  => $this->permalinkConfig->getPattern('topic'),
                'required' => ['id'],
            ],
            [
                'resource' => 'forum',
                'pattern'  => $this->permalinkConfig->getPattern('forum_page'),
                'required' => ['id', 'page'],
            ],
            [
                'resource' => 'forum',
                'pattern'  => $this->permalinkConfig->getPattern('forum'),
                'required' => ['id'],
            ],
            [
                'resource' => 'member',
                'pattern'  => $this->permalinkConfig->getPattern('member'),
                'required' => ['id'],
            ],
            [
                'resource' => 'group',
                'pattern'  => $groupPattern,
                'required' => ['id'],
            ],
        ];

        $compiled = [];
        foreach ($patterns as $item) {
            $compiledPattern = $this->compiler->compile($item['pattern'], $item['required']);
            $compiled[] = [
                'resource' => $item['resource'],
                'regex'    => $compiledPattern->getRegex(),
            ];
        }

        if (!is_dir($this->storeDirectory)) {
            @mkdir($this->storeDirectory, 0755, true);
        }

        $cacheFile = rtrim($this->storeDirectory, '/\\') . '/compiled_routes.php';
        $export = var_export($compiled, true);
        $content = "<?php\n// Auto-generated by phpBB SEO Framework — DO NOT EDIT MANUALLY\nreturn " . $export . ";\n";

        // Atomic write
        $tempFile = tempnam($this->storeDirectory, 'seo_route_');
        if ($tempFile !== false) {
            file_put_contents($tempFile, $content);
            @rename($tempFile, $cacheFile);
        } else {
            file_put_contents($cacheFile, $content);
        }

        return $compiled;
    }

    /**
     * Get compiled routes from cache file, rebuilding if missing.
     *
     * @return array<int, array<string, mixed>>
     */
    public function getRoutes(): array
    {
        $cacheFile = rtrim($this->storeDirectory, '/\\') . '/compiled_routes.php';
        if (file_exists($cacheFile)) {
            $routes = include $cacheFile;
            if (is_array($routes)) {
                return $routes;
            }
        }

        return $this->rebuild();
    }
}
